### ISSUE TITLE
Loop syntax label and lifetimes

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/dynamo#12]
I see you're sticking to some rust syntax, I always found loop labels and lifetimes to be too similar at first glance. Any chance you'd reconsider the single quote for something else? 

Perhaps:

```
@a: loop {
  break @a
}
```

Have you already discussed syntax? I'd enjoy reading it if so!

**Comment by bvssvni** [comment]
It should be possible to customize the syntax for your own taste. Just change this:

```
13 loop = [?["'" .._seps!:"label" ?w ":" ?w] "loop" .w!  block:"block"]
14 break = ["break" ?w ?["'" .._seps!:"label"]]
15 continue = ["continue" ?w ?["'" .._seps!:"label"]]
```

into

```
13 loop = [?["@" .._seps!:"label" ?w ":" ?w] "loop" .w!  block:"block"]
14 break = ["break" ?w ?["@" .._seps!:"label"]]
15 continue = ["continue" ?w ?["@" .._seps!:"label"]]
```

**Comment by bvssvni** [comment]
Meta syntax https://github.com/PistonDevelopers/dynamo/blob/master/assets/syntax.txt

**Comment by viperscape** [comment]
Fantastic!
