### ISSUE TITLE
Name collision with Dynamo BIM

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/dynamo#8]
Someone on reddit pointed out that Dynamo is already used by http://dynamobim.org/.

**Comment by tillarnold** [comment]
Man, naming things is hard... I'll try to make some new suggestions.

**Comment by cybergeek94** [comment]
I'm surprised that no one has used "crankshaft" for a Piston-related project, at least that I can find. It's not the most catchy name but it's relevant and suggests something with an important function.

**Comment by bvssvni** [comment]
Today, I got the idea of offering billionaires a 1 million usd price to name the language after themselves, or after their dog...

**Comment by bvssvni** [comment]
With other words, I've not come up with a name I like very much yet.

Hmm...

**Comment by bvssvni** [comment]
What about Gyro?

**Comment by bvssvni** [comment]
Another idea: Flywheel

**Comment by bvssvni** [comment]
Some other ideas:

- Nozzle
- Phaser
- Rocket

**Comment by bvssvni** [comment]
Corro - from corrosion

**Comment by MoSal** [comment]
Dust

**Comment by bvssvni** [comment]
Ozon

**Comment by bvssvni** [comment]
I was wondering, since Dynamo is a name of a non-trademarkable object, that we could use the name, but refer to it as Piston/Dynamo or DynamoScript to avoid confusion with Dynamo BIM.

**Comment by bvssvni** [comment]
I think I've found a perfect candidate: Dyon

https://en.wikipedia.org/wiki/Dyon

**Comment by bvssvni** [comment]
Suggestion from TechnoCrunch on IRC: Forch

It means dynamic, dashing in German.
